#
# Since: August, 2021
# Author: gvenzl
# Name: tests_load_mysql.yaml
# Description: GitHub Actions MySQL load tests
#
# Copyright 2021 Gerald Venzl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: load_tests_mysql
on: [push, pull_request]
jobs:
  db_load_tests:
    strategy:
      matrix:
        python-version: [ '3.6', '3.7', '3.8', '3.9', '3.x' ]

    runs-on: ubuntu-latest

    # Service container to run with "load_tests_mysql" job
    services:
      # MySQL service
      mysql-db:
        image: mysql
        env:
          MYSQL_USER: test
          MYSQL_ROOT_PASSWORD: LetsTest1
          MYSQL_DATABASE: test
        ports:
          - 3306:3306

    # Run tests
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install MySQL Driver
        run: python -m pip install mysql-connector-python
      - name: Setup test database
        run: |
          docker exec -i `docker ps -q` "mysql -u test -pLetsTest1 -D test" < test/resources/test_env/create_test_tables.sql
      - name: Run Python test on version ${{ matrix.python-version }}
        run: |
          export PYTHONPATH=$PWD/src/python
          cd test/python
          python tests_load_mysql.py